# Build front
FROM node:10 as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# npm
COPY package*.json /usr/src/app/
RUN npm ci

COPY . /usr/src/app
RUN npm run build

# Deploy Nginx Front
FROM nginx:1.15.2-alpine
COPY --from=builder /usr/src/app/public /var/www
COPY ./config/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx","-g","daemon off;"]